version: '3.8'

services:
  database:
    image: mongo:5.0
    container_name: order_database
    ports:
      - 27017:27017

  order:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - 5002:80
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://database:27017"
    depends_on:
      - database
